# col_isComplete
# col_hasCompleteness
# col_isUnique
# col_hasUniqueness
# col_hasDistinctness
# col_isInLOV
# col_isContainedIn
# col_hasConsistentType
# col_isNonNegative
# col_isLessThan
# col_isNotLessThan
# col_isGreaterThan
# col_isNotGreaterThan
# col_hasValue
# col_hasAllValues
# col_hasAnyValue
# col_satisfies
# col_satisfiesIf
# col_hasPredictability
# col_hasTypeConsistency
# col_hasCountDistinct
# col_hasMin
# col_hasMax
# col_hasMean
# col_hasStandardDeviation
# col_hasQuantile
# col_hasEntropy
# col_hasMutualInformation
# col_hasHistogramValue
# col_hasCorrelation
# col_hasNoAnomalies
